apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-shadow
  labels:
    app: aceest-fitness
    track: shadow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-fitness
      track: shadow
  template:
    metadata:
      labels:
        app: aceest-fitness
        track: shadow
    spec:
      containers:
      - name: aceest-fitness-container
        image: aniruddha404/aceest_fitness_app:latest
        ports:
        - containerPort: 5000

